### ISSUE TITLE
Use sandstorms PowerBox to access xkdb files

### ISSUE THREAD

**Issue by JamborJan** [JamborJan/keeweb-sandstorm#1]
Hey @mnutt, I would like to play around with PowerBox a bit. As this makes only sense when there is an app where I can pick a file from I wonder if you are interested as a counterpart for this? Furthermore I would need a partner here as the documentation is not that good yet / not existing. 

Let me know what you think.

(Ping @paulproteus FYI)

**Comment by mnutt** [comment]
I would absolutely be interested in playing around with Powerbox as well. I had only held off on it because my understanding was that the UI would change things significantly. Currently the way I understand it working is that you generate an offer request and then paste that into Davros, and at that point you'lll have webdav access to that Davros grain. My frontend already accesses files via webdav, so it should be fairly easy to turn that into a standalone library that can act as a filepicker. I can imagine the api looking like:

```javascript
filePicker(['read'], function(err, path) {
  if(!err) {
    return alert("Error: " + err);
  }

  $.get(path, function(data) { 
    // do something with data
  });
});
```

I could also imagine a nice promise-based version, but the callback version may be easiest to work with in a wide variety of apps.

The only thing I'm not sure about is if Sandstorm wants to special-case file picking and build their own UI for it.

**Comment by JamborJan** [comment]
WebDAV is perfect as KeeWeb supports that too with the latest version.

At the moment I have a very high level understanding of how PowerBox should work. From what I understood you tell the system than you can offer files. From my side I say, I need files. Sandstorm should display the PowerBox where I select Davros and the grain I want to access. What then happens: I don't know. I guess a UI you provide appears but I might be wrong.

Let's see, maybe @paulproteus or @zarvox can clarify this a bit ...

**Comment by paulproteus** [comment]
Yeah - there's an open question for now as to how this UI gets ​created. Is
it controlled by Sandstorm? Is it controlled (perhaps subject to some
security limitations) by apps themselves? But otherwise JanJambor, your
understanding is accurate.

For what it's worth, it's currently possible to use a "copy-paste powerbox"
where apps "offer" capabilities and other apps "consume" them. In that
approach, the interface is that Sandstorm provides a copy-pastable token,
like a GitHub API key, but this API key is only valid between two apps on
the same Sandstorm server.

We don't have docs written-up for that either, but if you're adventurous,
you can find some test apps in the Sandstorm test suite.

**Comment by JamborJan** [comment]
This project is dormant ([reasons](https://gist.github.com/JamborJan/8e42eff813b6fb0b6fe987afb9241c5e)). 

Issues will be closed as there will be no further progress on them. Feel free to fork the repo and take over maintenance.
