### ISSUE TITLE
App creation

### ISSUE THREAD

**Issue by yusf** [JamborJan/keeweb-sandstorm#2]
> when you want to fork this repo and create actual app packages for the app store

Sorry for weird question but is it that you don't plan on releasing this on Sandstorm? If so, what is left to do?

**Comment by JamborJan** [comment]
I totally plan to do that. At the moment you can use a pre-release here available on github. Download it and upload it to your sandstorm account. Let me know your feedback and I will try to include it.

For a first version there is some work to do to save the key save file in the grain. I'm not sure when it will be done but I hope in a few couple of days maybe weeks. 

A more sophisticated version including sandstorms power box to pick a file e.g. from Davros will take more time.

The sentence you mentioned is there because you cannot simply take the code and build the app and send it to the App Store. If you want to contribute feel free to fork the repo and send a pull request.

**Comment by yusf** [comment]
Thanks for outlining your plans, it sounds great. Non-coder here, but perhaps I can contribute in a bug-reporting capacity.

**Comment by JamborJan** [comment]
Short update: I did some improvements and we are not that far away from a first version for the Sandstorm app store. I'm waiting for some feedback from the upstream developer for some questions I had and then we are ready to go.

Will update this issue as soon as I know more.

**Comment by timshannon** [comment]
What's the status of this?

**Comment by JamborJan** [comment]
Hey @timshannon, thanks for reaching out. As you might have realized from the long time since the last updated in this thread I have been busy with some other things. 

First of all I have to check again wether the latest upstream version of keeweb supports saving a kdbx file on the server side now. This is is mandatory to have a single instance of the app including data in Sandstorm which allows the user to share the file and access to it.

I'm also not sure if realtime collaboration will work or not. According to the things I have seen at the [Sandpass repo](https://github.com/zombiezen/sandpass) this can be a tricky part.

Long answer short: I'll try to get a test version done within 2 to 3 weeks and update this repo with the results.

**Comment by timshannon** [comment]
Thanks for the update.  I agree, server side file storage is key for a sandstorm instance, but in my opinion the collaboration piece isn't a show stopper.   I personally can't see myself ever using it.

**Comment by JamborJan** [comment]
This project is dormant ([reasons](https://gist.github.com/JamborJan/8e42eff813b6fb0b6fe987afb9241c5e)). 

Issues will be closed as there will be no further progress on them. Feel free to fork the repo and take over maintenance.
