### ISSUE TITLE
Save password file in grain

### ISSUE THREAD

**Issue by JamborJan** [JamborJan/keeweb-sandstorm#3]
Keeweb is a fully client side web app and usually only stores its data to indexedDb / localStorage (see https://github.com/antelle/keeweb/issues/172).

So what happens when something should be saved in Sandstorm mode where indexedDb / localStorage is not available is this (from browsers error console):

```
[Error] 2016-03-28T09:08:35.344Z [storage-cache] Error opening indexed db
    error (app.js:1:20462)
    init (app.js:4:17230)
    save (app.js:4:17321)
    (anonyme Funktion) (app.js:4:4815)
    (anonyme Funktion) (app.js:3:2363)
    (anonyme Funktion)
    (anonyme Funktion) (vendor.js:8:14144)
    (anonyme Funktion) (vendor.js:8:19700)
    (anonyme Funktion)
    (anonyme Funktion)
```

I could now implement either something like Jason [did here](https://github.com/jparyani/laverna-sandstorm/issues/1#issuecomment-77812830) for the Laverna port for Sandstorm or I'm trying something different with other keeweb features.

**Comment by JamborJan** [comment]
Desired use-case as described also here: https://github.com/antelle/keeweb/issues/172
- user creates new instance of the app
- no password file is there so the user could create a new one or upload one
- when saving the file it is stored to /var (file is still encrypted + password protected and key file is not stored besides it)
- when the user opens the same instance again later, the app opens the existing configuration file **not** from localStorage, but from ```/var```
- same happens with the password save file
- the app should then directly show the input for the password to open the password file
- ideally it dosn't show the New and Open buttons any more then, but this an easy to customize thing then I guess

When the app is finally packed for sandstorm it should be possible to share a keeweb instance including password file with a department in case of a use-case in a company our with my spouse when talking about private usage. All available from all browsers and not bound to tools and an OS. The person I share the password file and the app with only needs to know the master password and if required needs the key file.

**Comment by mnutt** [comment]
Hey @JamborJan,

A while back I took a look at this and ended up hacking together something using the webdav storage backend + the webdav server from davros. You can find it here:

https://github.com/keeweb/keeweb/compare/develop...mnutt:sandstorm

The main things I changed were:

* Sandstorm-ish apps should really only have 1 db per grain, and that db is going to come from webdav. So disable all non-webdav options.
* The first thing it should do is ask you to set a master password, so I implemented a new view for creating a db. It bypasses the keepass webdav backend and saves directly to webdav to work around keepass not wanting to initially create the file.
* Enable auto-save for basically every action since we have no local storage and don't want to ever lose data.
* I was having problems with indexdb even after getting webdav working, so disabled saving to the cache completely.
* It doesn't allow initial uploading of a password file but that's something I'd like to add at some point.

You can test it out with this spk:

https://fltxj4bvh7yfw337mr1v.mnutt.sandcats.io/keeweb-beta.spk

I'll defer to you on publishing; feel free to take any or all of this for your package.

**Comment by JamborJan** [comment]
Awesome thanks @mnutt, I'll take a look at these points during the next days and will produce something people can use.

**Comment by JamborJan** [comment]
This project is dormant ([reasons](https://gist.github.com/JamborJan/8e42eff813b6fb0b6fe987afb9241c5e)). 

Issues will be closed as there will be no further progress on them. Feel free to fork the repo and take over maintenance.
